name: Create Cypress report
on:
  push:
    branches:
      - 'main'
jobs:
  cypress-e2e-chrome:
    name: Run on Chrome
    runs-on: ubuntu-latest
    container: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
    steps:
    - uses: actions/checkout@v3
    - name: Run Cypress tests
      run: npm run headlessChrome
      continue-on-error: true
    - name: Copy test execution videos
      run: |
        mkdir public
        cp -r cypress/videos public/videos
    - name: Generate HTML report
      run: npm run report:generate
    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
